apiVersion: v1
kind: Service
metadata:
  name: predict-backend-service
spec:
  type: LoadBalancer
  selector:
    app: predict-backend
  ports:
  - port: 3000
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-backend-deployment
spec:
  selector:
    matchLabels:
      app: predict-backend
  template:
    metadata:
      labels:
        app: predict-backend
    spec:
      containers:
      - name: predict-backend
        image: gcr.io/capstone-demo-350122/predict-backend-api:v1.5
        resources:
          # min resource request for gke autopilot
          # is cpu: 250m, memory: 512Mi, ephemeral-storage: 10Mi
          limits:
            cpu: 250m
            ephemeral-storage: 10Mi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 10Mi
            memory: 512Mi
        ports:
        - containerPort: 8080
